import { useState, type FormEvent, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "./api";

type Row = Record<string, any>;
type Section = "dashboard"|"kiosks"|"customers"|"contracts"|"rent"|"utilities"|"bills"|"requests"|"expenses"|"payments"|"reports"|"settings";
const sections: {id:Section;label:string;short?:string}[] = [
  {id:"dashboard",label:"Dashboard"},{id:"kiosks",label:"Kiosk"},{id:"customers",label:"Khách hàng"},{id:"contracts",label:"Hợp đồng"},
  {id:"rent",label:"Tiền thuê"},{id:"utilities",label:"Điện nước"},{id:"bills",label:"Bill"},{id:"requests",label:"Yêu cầu khách hàng",short:"Yêu cầu"},
  {id:"expenses",label:"Chi phí"},{id:"payments",label:"Thanh toán"},{id:"reports",label:"Báo cáo"},{id:"settings",label:"Cài đặt"},
];
const money=(n:number=0)=>new Intl.NumberFormat("vi-VN").format(n)+" ₫";
const dateVi=(s:string)=>new Intl.DateTimeFormat("vi-VN").format(new Date(`${s}T00:00:00`));
const statusClass=(s:string)=>s.includes("Đã")||s==="Đang hiệu lực"||s==="Đang cho thuê"?"success":s.includes("Quá")||s.includes("hết hạn")?"danger":s.includes("phần")||s.includes("xử lý")||s.includes("bảo trì")?"warn":"neutral";

function Badge({children}:{children:ReactNode}){return <span className={`badge ${statusClass(String(children))}`}>{children}</span>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><button className="icon-btn" aria-label="Đóng" onClick={onClose}>×</button></header>{children}</section></div>}
function Empty({text}:{text:string}){return <div className="empty"><strong>Chưa có dữ liệu</strong><p>{text}</p></div>}
function PageHead({title,desc,action}:{title:string;desc:string;action?:ReactNode}){return <div className="page-head"><div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Table({columns,rows,onOpen}:{columns:{key:string;label:string;render?:(r:Row)=>ReactNode}[];rows:Row[];onOpen?:(r:Row)=>void}){return rows.length?<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)} onClick={()=>onOpen?.(r)} className={onOpen?"clickable":""}>{columns.map(c=><td key={c.key} data-label={c.label}>{c.render?c.render(r):String(r[c.key]??"—")}</td>)}</tr>)}</tbody></table></div>:<Empty text="Hãy tạo bản ghi đầu tiên để bắt đầu."/>}

export function App(){
  const qc=useQueryClient(); const [section,setSection]=useState<Section>("dashboard"); const [navOpen,setNavOpen]=useState(false); const [modal,setModal]=useState<string|null>(null); const [selected,setSelected]=useState<Row|null>(null); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("Tất cả"); const [toast,setToast]=useState("");
  const q=useQuery({queryKey:["app-data"],queryFn:()=>api.getAppData({})});
  const refresh=()=>qc.invalidateQueries({queryKey:["app-data"]});
  const runMutation=(fn:(payload:any)=>Promise<{ok:boolean;message:string}>)=>useMutation({mutationFn:fn,onSuccess:(r)=>{setToast(r.message);if(r.ok){setModal(null);refresh()}setTimeout(()=>setToast(""),2600)}});
  const saveKiosk=runMutation((p)=>api.saveKiosk(p)); const deleteKiosk=runMutation((p)=>api.deleteKiosk(p)); const saveCustomer=runMutation((p)=>api.saveCustomer(p)); const deleteCustomer=runMutation((p)=>api.deleteCustomer(p)); const saveContract=runMutation((p)=>api.saveContract(p)); const deleteContract=runMutation((p)=>api.deleteContract(p)); const addReading=runMutation((p)=>api.addUtilityReading(p)); const createBills=runMutation((p)=>api.createMonthlyBills(p)); const payBill=runMutation((p)=>api.recordPayment(p)); const saveRequest=runMutation((p)=>api.saveRequest(p)); const updateRequest=runMutation((p)=>api.updateRequestStatus(p)); const saveExpense=runMutation((p)=>api.saveExpense(p)); const saveSettings=runMutation((p)=>api.saveSettings(p));
  const pdf=useMutation({mutationFn:(id:number)=>api.generateBillPdf({billId:id}),onSuccess:(r)=>{if(r.ok){const a=document.createElement("a");a.href=r.url;a.download=r.filename;a.click()}else setToast(r.message)}});
  const data=q.data; const kiosks=(data?.kiosks??[]) as Row[]; const customers=(data?.customers??[]) as Row[]; const contracts=(data?.contracts??[]) as Row[]; const bills=(data?.bills??[]) as Row[]; const readings=(data?.utilityReadings??[]) as Row[]; const requests=(data?.requests??[]) as Row[]; const expenses=(data?.expenses??[]) as Row[]; const payments=(data?.payments??[]) as Row[];
  const customerName=(id:number)=>customers.find(x=>x.id===id)?.name??"—"; const customerBrand=(id:number)=>customers.find(x=>x.id===id)?.brand??""; const kioskCode=(id:number)=>kiosks.find(x=>x.id===id)?.code??"—";
  const filtered=(rows:Row[],keys:string[])=>rows.filter(r=>{const hit=!search||keys.some(k=>String(r[k]??"").toLowerCase().includes(search.toLowerCase()));const ok=filter==="Tất cả"||r.status===filter;return hit&&ok});
  const navigate=(id:Section)=>{setSection(id);setNavOpen(false);setSearch("");setFilter("Tất cả")};
  if(q.isPending)return <div className="loading">Đang mở sổ quản lý…</div>;
  if(q.error)return <div className="loading"><strong>Không tải được dữ liệu.</strong><button onClick={()=>q.refetch()}>Thử lại</button></div>;
  const title=sections.find(x=>x.id===section)?.label??"Dashboard";
  return <div className="shell">
    <aside className={`sidebar ${navOpen?"open":""}`}><div className="org"><span className="org-mark">KC</span><div><strong>{data?.settings?.organizationName??"Ban quản lý kiosk"}</strong><small>Không gian vận hành</small></div></div><nav aria-label="Điều hướng chính">{sections.map(x=><button key={x.id} className={section===x.id?"active":""} onClick={()=>navigate(x.id)}>{x.label}</button>)}</nav><div className="side-note">MVP quản lý mặt bằng<br/><span>Dữ liệu được lưu tự động</span></div></aside>
    {navOpen&&<button className="nav-shade" aria-label="Đóng menu" onClick={()=>setNavOpen(false)}/>} 
    <main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setNavOpen(true)} aria-label="Mở menu">☰</button><div><strong>{title}</strong><span>{new Intl.DateTimeFormat("vi-VN",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date())}</span></div><button className="notice" aria-label="Xem thông báo" onClick={()=>navigate("dashboard")}>{(data?.notifications??[]).filter((n:Row)=>!n.read).length}</button></header><div className="content">
      {section==="dashboard"&&<Dashboard kiosks={kiosks} customers={customers} bills={bills} readings={readings} requests={requests} expenses={expenses} contracts={contracts} customerName={customerName} kioskCode={kioskCode} navigate={navigate}/>} 
      {section==="kiosks"&&<Kiosks rows={filtered(kiosks,["code","name","location"])} all={kiosks} customers={customers} contracts={contracts} bills={bills} readings={readings} requests={requests} expenses={expenses} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} onAdd={()=>{setSelected(null);setModal("kiosk")}} onOpen={r=>{setSelected(r);setModal("kiosk-detail")}}/>}
      {section==="customers"&&<Customers rows={filtered(customers,["name","brand","phone","email"])} contracts={contracts} kiosks={kiosks} bills={bills} requests={requests} search={search} setSearch={setSearch} onAdd={()=>{setSelected(null);setModal("customer")}} onOpen={r=>{setSelected(r);setModal("customer-detail")}}/>}
      {section==="contracts"&&<Contracts rows={filtered(contracts,["status"])} customers={customers} kiosks={kiosks} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} onAdd={()=>{setSelected(null);setModal("contract")}} onOpen={r=>{setSelected(r);setModal("contract-detail")}}/>}
      {section==="rent"&&<Rent bills={bills} customers={customers} kiosks={kiosks} onCreate={()=>setModal("create-bills")}/>} 
      {section==="utilities"&&<Utilities rows={readings} kiosks={kiosks} onAdd={()=>setModal("utility")}/>} 
      {section==="bills"&&<Bills rows={filtered(bills,["period","status"])} customers={customers} kiosks={kiosks} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} onOpen={r=>{setSelected(r);setModal("bill-detail")}}/>}
      {section==="requests"&&<Requests rows={requests} customers={customers} kiosks={kiosks} onAdd={()=>setModal("request")} onStatus={(id,status)=>updateRequest.mutate({id,status})}/>} 
      {section==="expenses"&&<Expenses rows={expenses} kiosks={kiosks} onAdd={()=>setModal("expense")}/>} 
      {section==="payments"&&<Payments bills={bills} payments={payments} customers={customers} kiosks={kiosks} onPay={r=>{setSelected(r);setModal("payment")}}/>}
      {section==="reports"&&<Reports bills={bills} expenses={expenses} kiosks={kiosks} customers={customers}/>} 
      {section==="settings"&&<SettingsPanel settings={data?.settings} onSubmit={p=>saveSettings.mutate(p)}/>} 
    </div></main>
    <nav className="bottom-nav" aria-label="Điều hướng nhanh">{([{id:"dashboard",label:"Tổng quan"},{id:"kiosks",label:"Kiosk"},{id:"bills",label:"Bill"},{id:"payments",label:"Thu tiền"}] as {id:Section;label:string}[]).map(x=><button key={x.id} className={section===x.id?"active":""} onClick={()=>navigate(x.id)}>{x.label}</button>)}<button onClick={()=>setNavOpen(true)}>Thêm</button></nav>
    {toast&&<div className="toast" role="status">{toast}</div>}
    {modal==="kiosk"&&<KioskForm initial={selected} onClose={()=>setModal(null)} onSubmit={p=>saveKiosk.mutate(p)}/>} 
    {modal==="kiosk-detail"&&selected&&<DetailModal title={`${selected.code} · ${selected.name}`} onClose={()=>setModal(null)} rows={[["Vị trí",selected.location],["Diện tích",`${selected.area} m²`],["Giá thuê",money(selected.baseRent)],["Tiền cọc",money(selected.deposit)],["Trạng thái",selected.status],["Ghi chú",selected.notes||"—"]]} sections={[{title:"Khách thuê & hợp đồng",text:(()=>{const c=contracts.find(x=>x.kioskId===selected.id);return c?`${customerName(c.customerId)} · ${c.startDate} → ${c.endDate}`:"Chưa có hợp đồng"})()},{title:"Lịch sử thanh toán",text:`${bills.filter(x=>x.kioskId===selected.id).length} bill · ${payments.filter(p=>bills.some(b=>b.id===p.billId&&b.kioskId===selected.id)).length} lần thu`},{title:"Điện nước",text:`${readings.filter(x=>x.kioskId===selected.id).length} kỳ đã nhập`},{title:"Yêu cầu & chi phí",text:`${requests.filter(x=>x.kioskId===selected.id).length} yêu cầu · ${expenses.filter(x=>x.kioskId===selected.id).length} chi phí`}]} actions={<><button onClick={()=>setModal("kiosk")}>Sửa</button><button className="danger-text" onClick={()=>deleteKiosk.mutate({id:selected.id})}>Xóa</button></>}/>} 
    {modal==="customer"&&<CustomerForm initial={selected} onClose={()=>setModal(null)} onSubmit={p=>saveCustomer.mutate(p)}/>} 
    {modal==="customer-detail"&&selected&&<DetailModal title={selected.name} onClose={()=>setModal(null)} rows={[["Thương hiệu",selected.brand],["Điện thoại",selected.phone],["Email",selected.email||"—"],["Địa chỉ",selected.address||"—"],["Người liên hệ",selected.contact||"—"],["CCCD / MST",selected.taxId||"—"],["Ghi chú",selected.notes||"—"]]} sections={[{title:"Hợp đồng",text:`${contracts.filter(x=>x.customerId===selected.id).length} hợp đồng`},{title:"Tiền thuê & thanh toán",text:`${bills.filter(x=>x.customerId===selected.id).length} bill · ${money(bills.filter(x=>x.customerId===selected.id).reduce((s,x)=>s+x.paidAmount,0))} đã thu`},{title:"Yêu cầu hỗ trợ",text:`${requests.filter(x=>x.customerId===selected.id).length} yêu cầu`}]} actions={<><button onClick={()=>setModal("customer")}>Sửa</button><button className="danger-text" onClick={()=>deleteCustomer.mutate({id:selected.id})}>Xóa</button></>}/>} 
    {modal==="contract"&&<ContractForm initial={selected} customers={customers} kiosks={kiosks} onClose={()=>setModal(null)} onSubmit={p=>saveContract.mutate(p)}/>} 
    {modal==="contract-detail"&&selected&&<DetailModal title={`Hợp đồng · ${kioskCode(selected.kioskId)}`} onClose={()=>setModal(null)} rows={[["Khách hàng",customerName(selected.customerId)],["Thời hạn",`${selected.startDate} → ${selected.endDate}`],["Giá thuê",money(selected.monthlyRent)],["Tiền cọc",money(selected.deposit)],["Ngày thanh toán",`Ngày ${selected.paymentDay} hàng tháng`],["Chu kỳ",selected.cycle],["Trạng thái",selected.status],["Điều khoản",selected.terms||"—"]]} actions={<><button onClick={()=>setModal("contract")}>Sửa</button><button className="danger-text" onClick={()=>deleteContract.mutate({id:selected.id})}>Xóa</button></>}/>} 
    {modal==="utility"&&<UtilityForm kiosks={kiosks} settings={data?.settings} onClose={()=>setModal(null)} onSubmit={p=>addReading.mutate(p)}/>} 
    {modal==="create-bills"&&<CreateBillForm onClose={()=>setModal(null)} onSubmit={period=>createBills.mutate({period})}/>} 
    {modal==="bill-detail"&&selected&&<BillDetail bill={selected} customer={customers.find(x=>x.id===selected.customerId)} kiosk={kiosks.find(x=>x.id===selected.kioskId)} onClose={()=>setModal(null)} onPay={()=>setModal("payment")} onPdf={()=>pdf.mutate(selected.id)}/>} 
    {modal==="payment"&&selected&&<PaymentForm bill={selected} onClose={()=>setModal(null)} onSubmit={p=>payBill.mutate(p)}/>} 
    {modal==="request"&&<RequestForm customers={customers} kiosks={kiosks} onClose={()=>setModal(null)} onSubmit={p=>saveRequest.mutate(p)}/>} 
    {modal==="expense"&&<ExpenseForm kiosks={kiosks} onClose={()=>setModal(null)} onSubmit={p=>saveExpense.mutate(p)}/>} 
  </div>
}

function Dashboard({kiosks,customers,bills,readings,requests,expenses,contracts,customerName,kioskCode,navigate}:{kiosks:Row[];customers:Row[];bills:Row[];readings:Row[];requests:Row[];expenses:Row[];contracts:Row[];customerName:(id:number)=>string;kioskCode:(id:number)=>string;navigate:(s:Section)=>void}){
  const current=bills.filter(b=>b.period==="2026-10"); const occupied=kiosks.filter(k=>k.status==="Đang cho thuê").length; const unpaid=bills.reduce((s,b)=>s+Math.max(0,b.total-b.paidAmount),0); const open=requests.filter(r=>!["Đã hoàn thành","Đã đóng"].includes(r.status)); const due=[...bills].filter(b=>b.paidAmount<b.total).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5);
  const revenue=Array.from(new Set(bills.map(b=>b.period))).sort().map(period=>({period:String(period).slice(5),"Đã thu":bills.filter(b=>b.period===period).reduce((s,b)=>s+b.paidAmount,0)/1000000})); const expiring=contracts.filter(c=>c.status==="Sắp hết hạn"||c.status==="Đã hết hạn");
  return <><div className="dashboard-intro"><div><span className="date-kicker">VIỆC CẦN XỬ LÝ</span><h1>{unpaid>0?money(unpaid):"Không có công nợ"}</h1><p>Tổng công nợ đang theo dõi trên {bills.filter(b=>b.paidAmount<b.total).length} bill.</p></div><button onClick={()=>navigate("payments")}>Xem & ghi nhận thu</button></div>
  <div className="stats"><div><small>Kiosk</small><strong>{occupied}/{kiosks.length}</strong><span>{kiosks.length-occupied} chưa cho thuê</span></div><div><small>Khách đang thuê</small><strong>{customers.length}</strong><span>{expiring.length} hợp đồng cần chú ý</span></div><div><small>Tiền thuê tháng 10</small><strong>{money(current.reduce((s,b)=>s+b.rent,0))}</strong><span>Điện {money(current.reduce((s,b)=>s+b.electric,0))}</span></div><div><small>Yêu cầu chưa xong</small><strong>{open.length}</strong><span>{open.filter(r=>r.priority==="Cao").length} ưu tiên cao</span></div></div>
  <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-title"><div><h2>Doanh thu đã thu</h2><p>Triệu đồng theo tháng</p></div><Badge>{revenue.length?`${revenue.length} tháng`:"Chưa có"}</Badge></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={revenue}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period"/><YAxis domain={[0,"auto"]} width={34}/><Tooltip formatter={(v)=>`${v} triệu ₫`} labelFormatter={l=>`Tháng ${l}`}/><Bar dataKey="Đã thu" fill="#139A78" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section>
  <section className="panel"><div className="panel-title"><div><h2>Khoản cần thu gần nhất</h2><p>Theo hạn thanh toán</p></div><button className="link-btn" onClick={()=>navigate("bills")}>Tất cả</button></div><div className="compact-list">{due.map(b=><button key={b.id} onClick={()=>navigate("payments")}><span><strong>{customerName(b.customerId)}</strong><small>{kioskCode(b.kioskId)} · hạn {dateVi(b.dueDate)}</small></span><b>{money(b.total-b.paidAmount)}</b></button>)}</div></section>
  <section className="panel"><div className="panel-title"><div><h2>Yêu cầu mới nhất</h2><p>Hỗ trợ khách thuê</p></div><button className="link-btn" onClick={()=>navigate("requests")}>Mở danh sách</button></div><div className="ticket-list">{open.slice(0,4).map(r=><div key={r.id}><span className={`priority ${r.priority==="Cao"?"high":""}`}></span><div><strong>{r.content}</strong><small>{kioskCode(r.kioskId)} · {r.type}</small></div><Badge>{r.status}</Badge></div>)}</div></section>
  <section className="panel"><div className="panel-title"><div><h2>Tình trạng tháng này</h2><p>Tổng hợp từ bill và chỉ số</p></div></div><div className="payment-bars">{[["Đã thu",current.reduce((s,b)=>s+b.paidAmount,0),"good"],["Còn phải thu",current.reduce((s,b)=>s+b.total-b.paidAmount,0),"bad"],["Điện nước",current.reduce((s,b)=>s+b.electric+b.water,0),"info"],["Chi phí",expenses.filter(e=>e.date.startsWith("2026-10")).reduce((s,e)=>s+e.amount,0),"muted"]].map(([label,value,tone])=><div key={String(label)}><span>{label}</span><strong>{money(Number(value))}</strong><i className={String(tone)} style={{width:`${Math.min(100,Number(value)/(Math.max(1,current.reduce((s,b)=>s+b.total,0)))*100)}%`}}/></div>)}</div></section></div></>
}

function Toolbar({search,setSearch,filter,setFilter,options,onAdd,addLabel}:{search:string;setSearch:(s:string)=>void;filter?:string;setFilter?:(s:string)=>void;options?:string[];onAdd:()=>void;addLabel:string}){return <div className="toolbar"><input aria-label="Tìm kiếm" placeholder="Tìm kiếm…" value={search} onChange={e=>setSearch(e.target.value)}/>{filter!==undefined&&setFilter&&<select aria-label="Lọc trạng thái" value={filter} onChange={e=>setFilter(e.target.value)}>{["Tất cả",...(options??[])].map(x=><option key={x}>{x}</option>)}</select>}<button onClick={onAdd}>+ {addLabel}</button></div>}
function Kiosks({rows,customers,contracts,bills,readings,requests,expenses,search,setSearch,filter,setFilter,onAdd,onOpen}:{rows:Row[];all:Row[];customers:Row[];contracts:Row[];bills:Row[];readings:Row[];requests:Row[];expenses:Row[];search:string;setSearch:(s:string)=>void;filter:string;setFilter:(s:string)=>void;onAdd:()=>void;onOpen:(r:Row)=>void}){return <><PageHead title="Danh sách kiosk" desc="Theo dõi tình trạng, giá thuê và hồ sơ từng mặt bằng."/><Toolbar {...{search,setSearch,filter,setFilter,onAdd}} options={["Đang cho thuê","Còn trống","Đang bảo trì"]} addLabel="Thêm kiosk"/><Table rows={rows} onOpen={onOpen} columns={[{key:"code",label:"Mã",render:r=><strong>{r.code}</strong>},{key:"name",label:"Kiosk"},{key:"location",label:"Vị trí"},{key:"area",label:"Diện tích",render:r=>`${r.area} m²`},{key:"baseRent",label:"Giá thuê",render:r=>money(r.baseRent)},{key:"status",label:"Trạng thái",render:r=><Badge>{r.status}</Badge>},{key:"tenant",label:"Khách thuê",render:r=>{const c=contracts.find(x=>x.kioskId===r.id&&x.status!=="Đã chấm dứt");return c?customers.find(x=>x.id===c.customerId)?.brand??"—":"—"}}]}/></>}
function Customers({rows,contracts,kiosks,bills,requests,search,setSearch,onAdd,onOpen}:{rows:Row[];contracts:Row[];kiosks:Row[];bills:Row[];requests:Row[];search:string;setSearch:(s:string)=>void;onAdd:()=>void;onOpen:(r:Row)=>void}){return <><PageHead title="Khách hàng" desc="Hồ sơ khách thuê và toàn bộ lịch sử liên quan."/><Toolbar search={search} setSearch={setSearch} onAdd={onAdd} addLabel="Thêm khách hàng"/><Table rows={rows} onOpen={onOpen} columns={[{key:"name",label:"Khách hàng",render:r=><span><strong>{r.name}</strong><small className="cell-sub">{r.brand}</small></span>},{key:"phone",label:"Điện thoại"},{key:"email",label:"Email"},{key:"kiosk",label:"Kiosk đang thuê",render:r=>{const c=contracts.find(x=>x.customerId===r.id&&x.status!=="Đã chấm dứt");return kiosks.find(x=>x.id===c?.kioskId)?.code??"—"}},{key:"status",label:"Hợp đồng",render:r=>{const c=contracts.find(x=>x.customerId===r.id);return c?<Badge>{c.status}</Badge>:"—"}}]}/></>}
function Contracts({rows,customers,kiosks,search,setSearch,filter,setFilter,onAdd,onOpen}:{rows:Row[];customers:Row[];kiosks:Row[];search:string;setSearch:(s:string)=>void;filter:string;setFilter:(s:string)=>void;onAdd:()=>void;onOpen:(r:Row)=>void}){return <><PageHead title="Hợp đồng" desc="Quản lý thời hạn, tiền cọc và chu kỳ thanh toán."/><Toolbar {...{search,setSearch,filter,setFilter,onAdd}} options={["Đang hiệu lực","Sắp hết hạn","Đã hết hạn","Đã chấm dứt"]} addLabel="Tạo hợp đồng"/><Table rows={rows} onOpen={onOpen} columns={[{key:"kiosk",label:"Kiosk",render:r=><strong>{kiosks.find(x=>x.id===r.kioskId)?.code??"—"}</strong>},{key:"customer",label:"Khách hàng",render:r=>customers.find(x=>x.id===r.customerId)?.name??"—"},{key:"period",label:"Thời hạn",render:r=><span>{dateVi(r.startDate)}<small className="cell-sub">đến {dateVi(r.endDate)}</small></span>},{key:"rent",label:"Giá thuê/tháng",render:r=>money(r.monthlyRent)},{key:"status",label:"Trạng thái",render:r=><Badge>{r.status}</Badge>}]}/></>}
function Rent({bills,customers,kiosks,onCreate}:{bills:Row[];customers:Row[];kiosks:Row[];onCreate:()=>void}){const rents=bills.map(b=>({...b,other:b.otherFee+b.managementFee+b.serviceFee,totalRent:b.rent+b.otherFee-b.discount}));return <><PageHead title="Tiền thuê hàng tháng" desc="Khoản thuê được tổng hợp vào bill theo từng kỳ." action={<button className="primary" onClick={onCreate}>Tạo bill theo kỳ</button>}/><Table rows={rents} columns={[{key:"period",label:"Kỳ"},{key:"customer",label:"Khách hàng",render:r=>customers.find(x=>x.id===r.customerId)?.name??"—"},{key:"kiosk",label:"Kiosk",render:r=>kiosks.find(x=>x.id===r.kioskId)?.code??"—"},{key:"rent",label:"Tiền thuê",render:r=>money(r.rent)},{key:"other",label:"Phí khác",render:r=>money(r.other)},{key:"discount",label:"Giảm giá",render:r=>money(r.discount)},{key:"totalRent",label:"Tổng tiền thuê",render:r=><strong>{money(r.totalRent)}</strong>},{key:"status",label:"Trạng thái",render:r=><Badge>{r.status}</Badge>}]}/></>}
function Utilities({rows,kiosks,onAdd}:{rows:Row[];kiosks:Row[];onAdd:()=>void}){return <><PageHead title="Điện nước" desc="Nhập chỉ số và kiểm tra mức tiêu thụ theo kỳ." action={<button className="primary" onClick={onAdd}>+ Nhập chỉ số</button>}/><Table rows={rows} columns={[{key:"period",label:"Kỳ"},{key:"kiosk",label:"Kiosk",render:r=><strong>{kiosks.find(x=>x.id===r.kioskId)?.code??"—"}</strong>},{key:"electric",label:"Điện",render:r=><span>{r.electricCurrent-r.electricPrevious} kWh<small className="cell-sub">{money((r.electricCurrent-r.electricPrevious)*r.electricRate)}</small></span>},{key:"water",label:"Nước",render:r=><span>{r.waterCurrent-r.waterPrevious} m³<small className="cell-sub">{money((r.waterCurrent-r.waterPrevious)*r.waterRate)}</small></span>},{key:"fees",label:"Phí dịch vụ",render:r=>money(r.cleaningFee+r.managementFee+r.serviceFee+r.otherFee)},{key:"total",label:"Tổng điện nước",render:r=><strong>{money((r.electricCurrent-r.electricPrevious)*r.electricRate+(r.waterCurrent-r.waterPrevious)*r.waterRate)}</strong>}]}/></>}
function Bills({rows,customers,kiosks,search,setSearch,filter,setFilter,onOpen}:{rows:Row[];customers:Row[];kiosks:Row[];search:string;setSearch:(s:string)=>void;filter:string;setFilter:(s:string)=>void;onOpen:(r:Row)=>void}){return <><PageHead title="Bill hàng tháng" desc="Xem chi tiết, theo dõi hạn và xuất PDF gửi khách hàng."/><Toolbar {...{search,setSearch,filter,setFilter}} onAdd={()=>{}} addLabel="" options={["Chưa thanh toán","Đã thanh toán","Quá hạn","Thanh toán một phần"]}/><Table rows={rows} onOpen={onOpen} columns={[{key:"period",label:"Kỳ",render:r=><strong>{r.period}</strong>},{key:"customer",label:"Khách hàng",render:r=><span>{customers.find(x=>x.id===r.customerId)?.name??"—"}<small className="cell-sub">{customers.find(x=>x.id===r.customerId)?.brand}</small></span>},{key:"kiosk",label:"Kiosk",render:r=>kiosks.find(x=>x.id===r.kioskId)?.code??"—"},{key:"dueDate",label:"Hạn thanh toán",render:r=>dateVi(r.dueDate)},{key:"total",label:"Tổng tiền",render:r=><strong>{money(r.total)}</strong>},{key:"status",label:"Trạng thái",render:r=><Badge>{r.status}</Badge>}]}/></>}
function Requests({rows,customers,kiosks,onAdd,onStatus}:{rows:Row[];customers:Row[];kiosks:Row[];onAdd:()=>void;onStatus:(id:number,status:string)=>void}){return <><PageHead title="Yêu cầu khách hàng" desc="Tiếp nhận và theo dõi tiến độ xử lý tại kiosk." action={<button className="primary" onClick={onAdd}>+ Tạo yêu cầu</button>}/><div className="request-grid">{rows.map(r=><article className="request-card" key={r.id}><div><span className={`priority ${r.priority==="Cao"?"high":""}`}></span><small>{r.code} · {r.type}</small><Badge>{r.priority}</Badge></div><h3>{r.content}</h3><p>{customers.find(x=>x.id===r.customerId)?.brand} · {kiosks.find(x=>x.id===r.kioskId)?.code}</p><footer><select aria-label={`Trạng thái ${r.code}`} value={r.status} onChange={e=>onStatus(r.id,e.target.value)}>{["Mới","Đang xử lý","Chờ khách hàng","Đã hoàn thành","Đã đóng"].map(x=><option key={x}>{x}</option>)}</select><span>{r.assignee||"Chưa phân công"}</span></footer></article>)}</div></>}
function Expenses({rows,kiosks,onAdd}:{rows:Row[];kiosks:Row[];onAdd:()=>void}){return <><PageHead title="Chi phí phát sinh" desc="Theo dõi chi phí vận hành và khoản đưa vào bill khách thuê." action={<button className="primary" onClick={onAdd}>+ Thêm chi phí</button>}/><Table rows={rows} columns={[{key:"date",label:"Ngày",render:r=>dateVi(r.date)},{key:"type",label:"Loại"},{key:"content",label:"Nội dung"},{key:"kiosk",label:"Kiosk",render:r=>kiosks.find(x=>x.id===r.kioskId)?.code??"Chung"},{key:"amount",label:"Số tiền",render:r=><strong>{money(r.amount)}</strong>},{key:"payer",label:"Bên chịu"},{key:"addToBill",label:"Đưa vào bill",render:r=>r.addToBill?<Badge>Có</Badge>:"Không"}]}/></>}
function Payments({bills,payments,customers,kiosks,onPay}:{bills:Row[];payments:Row[];customers:Row[];kiosks:Row[];onPay:(r:Row)=>void}){const total=bills.reduce((s,b)=>s+b.total,0),paid=bills.reduce((s,b)=>s+b.paidAmount,0),overdue=bills.filter(b=>b.status==="Quá hạn").reduce((s,b)=>s+b.total-b.paidAmount,0);return <><PageHead title="Theo dõi thanh toán" desc="Ghi nhận thanh toán đủ hoặc từng phần theo bill."/><div className="mini-stats"><div><span>Tổng phải thu</span><strong>{money(total)}</strong></div><div><span>Đã thu</span><strong>{money(paid)}</strong></div><div><span>Còn phải thu</span><strong>{money(total-paid)}</strong></div><div><span>Quá hạn</span><strong>{money(overdue)}</strong></div></div><Table rows={bills} columns={[{key:"period",label:"Kỳ"},{key:"customer",label:"Khách hàng",render:r=>customers.find(x=>x.id===r.customerId)?.name??"—"},{key:"kiosk",label:"Kiosk",render:r=>kiosks.find(x=>x.id===r.kioskId)?.code??"—"},{key:"total",label:"Phải thu",render:r=>money(r.total)},{key:"paid",label:"Đã thu",render:r=>money(r.paidAmount)},{key:"remaining",label:"Còn lại",render:r=><strong>{money(r.total-r.paidAmount)}</strong>},{key:"action",label:"",render:r=>r.paidAmount<r.total?<button className="small-btn" onClick={(e)=>{e.stopPropagation();onPay(r)}}>Ghi nhận thu</button>:<Badge>Hoàn tất</Badge>}]}/><section className="panel history"><div className="panel-title"><div><h2>Lịch sử thu gần đây</h2><p>{payments.length} giao dịch</p></div></div>{payments.slice(0,8).map(p=><div className="history-row" key={p.id}><span>{dateVi(p.paymentDate)}</span><span>{p.method}</span><strong>{money(p.amount)}</strong></div>)}</section></>}
function Reports({bills,expenses,kiosks,customers}:{bills:Row[];expenses:Row[];kiosks:Row[];customers:Row[]}){const [from,setFrom]=useState("2026-06");const [to,setTo]=useState("2026-10");const subset=bills.filter(b=>b.period>=from&&b.period<=to);const rev=subset.reduce((s,b)=>s+b.paidAmount,0),cost=expenses.filter(e=>e.date.slice(0,7)>=from&&e.date.slice(0,7)<=to).reduce((s,e)=>s+e.amount,0);const chart=Array.from(new Set(subset.map(b=>b.period))).sort().map(period=>({period,"Doanh thu":subset.filter(b=>b.period===period).reduce((s,b)=>s+b.paidAmount,0)/1000000,"Chi phí":expenses.filter(e=>e.date.startsWith(period)).reduce((s,e)=>s+e.amount,0)/1000000}));const exportCsv=()=>{const rows=[["Kỳ","Kiosk","Khách hàng","Tổng bill","Đã thu","Công nợ"],...subset.map(b=>[b.period,kiosks.find(k=>k.id===b.kioskId)?.code??"",customers.find(c=>c.id===b.customerId)?.name??"",b.total,b.paidAmount,b.total-b.paidAmount])];const blob=new Blob(["\ufeff"+rows.map(r=>r.join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`bao-cao-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)};return <><PageHead title="Báo cáo" desc="Doanh thu, công nợ và lợi nhuận ước tính theo khoảng thời gian." action={<button className="primary" onClick={exportCsv}>Xuất CSV</button>}/><div className="range"><Field label="Từ tháng"><input type="month" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Đến tháng"><input type="month" value={to} onChange={e=>setTo(e.target.value)}/></Field></div><div className="mini-stats"><div><span>Doanh thu đã thu</span><strong>{money(rev)}</strong></div><div><span>Doanh thu điện nước</span><strong>{money(subset.reduce((s,b)=>s+b.electric+b.water,0))}</strong></div><div><span>Chi phí phát sinh</span><strong>{money(cost)}</strong></div><div><span>Lợi nhuận ước tính</span><strong>{money(rev-cost)}</strong></div></div><section className="panel chart-panel wide"><div className="panel-title"><div><h2>Doanh thu và chi phí</h2><p>Đơn vị: triệu đồng</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period"/><YAxis domain={[0,"auto"]}/><Tooltip/><Bar dataKey="Doanh thu" fill="#173F5F" radius={[4,4,0,0]}/><Bar dataKey="Chi phí" fill="#E47A3F" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section></>}
function SettingsPanel({settings,onSubmit}:{settings:Row|null;onSubmit:(p:any)=>void}){const [form,setForm]=useState<Row>(settings??{organizationName:"",address:"",phone:"",email:"",electricRate:3500,waterRate:18000,managementFee:300000,billDay:1,dueDay:5});const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));return <><PageHead title="Cài đặt" desc="Thông tin đơn vị và các mức phí mặc định."/><form className="settings-form" onSubmit={e=>{e.preventDefault();onSubmit(form)}}><section><h2>Thông tin đơn vị</h2><div className="form-grid"><Field label="Tên đơn vị"><input value={form.organizationName} onChange={e=>set("organizationName",e.target.value)} required/></Field><Field label="Số điện thoại"><input value={form.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Địa chỉ"><input value={form.address} onChange={e=>set("address",e.target.value)}/></Field></div></section><section><h2>Đơn giá & kỳ bill</h2><div className="form-grid"><Field label="Đơn giá điện (₫/kWh)"><input type="number" value={form.electricRate} onChange={e=>set("electricRate",Number(e.target.value))}/></Field><Field label="Đơn giá nước (₫/m³)"><input type="number" value={form.waterRate} onChange={e=>set("waterRate",Number(e.target.value))}/></Field><Field label="Phí quản lý mặc định"><input type="number" value={form.managementFee} onChange={e=>set("managementFee",Number(e.target.value))}/></Field><Field label="Ngày tạo bill"><input type="number" min="1" max="28" value={form.billDay} onChange={e=>set("billDay",Number(e.target.value))}/></Field><Field label="Ngày đến hạn"><input type="number" min="1" max="28" value={form.dueDay} onChange={e=>set("dueDay",Number(e.target.value))}/></Field></div></section><button className="primary" type="submit">Lưu cài đặt</button></form></>}

function KioskForm({initial,onClose,onSubmit}:{initial:Row|null;onClose:()=>void;onSubmit:(p:any)=>void}){const [f,setF]=useState<Row>(initial??{code:"",name:"",location:"",area:15,baseRent:0,status:"Còn trống",deposit:0,notes:""});return <FormModal title={initial?"Sửa kiosk":"Thêm kiosk"} onClose={onClose} onSubmit={()=>onSubmit(f)}><TextFields form={f} setForm={setF} fields={[["code","Mã kiosk"],["name","Tên kiosk"],["location","Vị trí"],["area","Diện tích (m²)","number"],["baseRent","Giá thuê cơ bản","number"],["deposit","Tiền cọc","number"]]}/><Field label="Trạng thái"><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{["Đang cho thuê","Còn trống","Đang bảo trì"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Ghi chú"><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></FormModal>}
function CustomerForm({initial,onClose,onSubmit}:{initial:Row|null;onClose:()=>void;onSubmit:(p:any)=>void}){const [f,setF]=useState<Row>(initial??{name:"",brand:"",phone:"",email:"",address:"",contact:"",taxId:"",notes:""});return <FormModal title={initial?"Sửa khách hàng":"Thêm khách hàng"} onClose={onClose} onSubmit={()=>onSubmit(f)}><TextFields form={f} setForm={setF} fields={[["name","Tên khách hàng"],["brand","Cửa hàng / thương hiệu"],["phone","Số điện thoại"],["email","Email","email"],["address","Địa chỉ"],["contact","Người liên hệ"],["taxId","CCCD / MST"]]}/><Field label="Ghi chú"><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></FormModal>}
function ContractForm({initial,customers,kiosks,onClose,onSubmit}:{initial:Row|null;customers:Row[];kiosks:Row[];onClose:()=>void;onSubmit:(p:any)=>void}){const [f,setF]=useState<Row>(initial??{customerId:customers[0]?.id??0,kioskId:kiosks[0]?.id??0,startDate:"2026-10-01",endDate:"2027-09-30",monthlyRent:0,deposit:0,paymentDay:5,cycle:"Hàng tháng",terms:"",status:"Đang hiệu lực"});return <FormModal title={initial?"Sửa hợp đồng":"Tạo hợp đồng"} onClose={onClose} onSubmit={()=>onSubmit(f)}><Field label="Khách hàng"><select value={f.customerId} onChange={e=>setF({...f,customerId:Number(e.target.value)})}>{customers.map(x=><option value={x.id} key={x.id}>{x.name} · {x.brand}</option>)}</select></Field><Field label="Kiosk"><select value={f.kioskId} onChange={e=>setF({...f,kioskId:Number(e.target.value)})}>{kiosks.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></Field><TextFields form={f} setForm={setF} fields={[["startDate","Ngày bắt đầu","date"],["endDate","Ngày kết thúc","date"],["monthlyRent","Giá thuê/tháng","number"],["deposit","Tiền cọc","number"],["paymentDay","Ngày thanh toán","number"]]}/><Field label="Trạng thái"><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{["Đang hiệu lực","Sắp hết hạn","Đã hết hạn","Đã chấm dứt"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Điều khoản / ghi chú"><textarea value={f.terms} onChange={e=>setF({...f,terms:e.target.value})}/></Field></FormModal>}
function UtilityForm({kiosks,settings,onClose,onSubmit}:{kiosks:Row[];settings:Row|null;onClose:()=>void;onSubmit:(p:any)=>void}){const [f,setF]=useState<Row>({kioskId:kiosks[0]?.id??0,period:"2026-10",electricPrevious:0,electricCurrent:0,electricRate:settings?.electricRate??3500,waterPrevious:0,waterCurrent:0,waterRate:settings?.waterRate??18000,cleaningFee:0,managementFee:settings?.managementFee??0,serviceFee:0,otherFee:0});const e=(f.electricCurrent-f.electricPrevious)*f.electricRate,w=(f.waterCurrent-f.waterPrevious)*f.waterRate;return <FormModal title="Nhập chỉ số điện nước" onClose={onClose} onSubmit={()=>onSubmit(f)}><Field label="Kiosk"><select value={f.kioskId} onChange={x=>setF({...f,kioskId:Number(x.target.value)})}>{kiosks.map(k=><option value={k.id} key={k.id}>{k.code}</option>)}</select></Field><Field label="Kỳ"><input type="month" value={f.period} onChange={e=>setF({...f,period:e.target.value})}/></Field><div className="form-section">Điện</div><TextFields form={f} setForm={setF} fields={[["electricPrevious","Chỉ số kỳ trước","number"],["electricCurrent","Chỉ số kỳ này","number"],["electricRate","Đơn giá điện","number"]]}/><div className="calc">Tiêu thụ {Math.max(0,f.electricCurrent-f.electricPrevious)} kWh · <strong>{money(Math.max(0,e))}</strong></div><div className="form-section">Nước</div><TextFields form={f} setForm={setF} fields={[["waterPrevious","Chỉ số kỳ trước","number"],["waterCurrent","Chỉ số kỳ này","number"],["waterRate","Đơn giá nước","number"]]}/><div className="calc">Tiêu thụ {Math.max(0,f.waterCurrent-f.waterPrevious)} m³ · <strong>{money(Math.max(0,w))}</strong></div><TextFields form={f} setForm={setF} fields={[["cleaningFee","Phí vệ sinh","number"],["managementFee","Phí quản lý","number"],["serviceFee","Phí dịch vụ","number"],["otherFee","Phí khác","number"]]}/></FormModal>}
function CreateBillForm({onClose,onSubmit}:{onClose:()=>void;onSubmit:(p:string)=>void}){const [period,setPeriod]=useState("2026-10");return <FormModal title="Tạo bill theo kỳ" onClose={onClose} onSubmit={()=>onSubmit(period)}><p className="form-help">Hệ thống tạo bill cho hợp đồng đang hiệu lực và tự lấy chỉ số điện nước cùng kỳ. Bill đã tồn tại sẽ được bỏ qua.</p><Field label="Kỳ thanh toán"><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></Field></FormModal>}
function PaymentForm({bill,onClose,onSubmit}:{bill:Row;onClose:()=>void;onSubmit:(p:any)=>void}){const remain=bill.total-bill.paidAmount;const [f,setF]=useState<Row>({billId:bill.id,amount:remain,paymentDate:new Date().toISOString().slice(0,10),method:"Chuyển khoản",notes:""});return <FormModal title="Ghi nhận thanh toán" onClose={onClose} onSubmit={()=>onSubmit(f)}><div className="amount-due"><span>Còn phải thu</span><strong>{money(remain)}</strong></div><Field label="Số tiền nhận"><input type="number" min="1" max={remain} value={f.amount} onChange={e=>setF({...f,amount:Number(e.target.value)})}/></Field><Field label="Ngày thanh toán"><input type="date" value={f.paymentDate} onChange={e=>setF({...f,paymentDate:e.target.value})}/></Field><Field label="Phương thức"><select value={f.method} onChange={e=>setF({...f,method:e.target.value})}>{["Chuyển khoản","Tiền mặt","Khác"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Ghi chú"><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></FormModal>}
function RequestForm({customers,kiosks,onClose,onSubmit}:{customers:Row[];kiosks:Row[];onClose:()=>void;onSubmit:(p:any)=>void}){const [f,setF]=useState<Row>({customerId:customers[0]?.id??0,kioskId:kiosks[0]?.id??0,content:"",type:"Sửa điện",priority:"Trung bình",assignee:"",status:"Mới",notes:"",repairCost:0});return <FormModal title="Tạo yêu cầu khách hàng" onClose={onClose} onSubmit={()=>onSubmit(f)}><Field label="Khách hàng"><select value={f.customerId} onChange={e=>setF({...f,customerId:Number(e.target.value)})}>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Kiosk"><select value={f.kioskId} onChange={e=>setF({...f,kioskId:Number(e.target.value)})}>{kiosks.map(k=><option value={k.id} key={k.id}>{k.code}</option>)}</select></Field><Field label="Loại yêu cầu"><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{["Sửa điện","Sửa nước","Điều hòa","Vệ sinh","Sửa chữa kiosk","Internet","Biển hiệu","Thay bóng đèn","Khác"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Nội dung"><textarea required value={f.content} onChange={e=>setF({...f,content:e.target.value})}/></Field><Field label="Mức độ ưu tiên"><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}>{["Thấp","Trung bình","Cao"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Người phụ trách"><input value={f.assignee} onChange={e=>setF({...f,assignee:e.target.value})}/></Field></FormModal>}
function ExpenseForm({kiosks,onClose,onSubmit}:{kiosks:Row[];onClose:()=>void;onSubmit:(p:any)=>void}){const [f,setF]=useState<Row>({date:new Date().toISOString().slice(0,10),kioskId:null,type:"Sửa chữa",content:"",amount:0,enteredBy:"Quản lý",payer:"Chủ mặt bằng",addToBill:false,notes:""});return <FormModal title="Thêm chi phí" onClose={onClose} onSubmit={()=>onSubmit(f)}><Field label="Ngày"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Kiosk"><select value={f.kioskId??""} onChange={e=>setF({...f,kioskId:e.target.value?Number(e.target.value):null})}><option value="">Chi phí chung</option>{kiosks.map(k=><option value={k.id} key={k.id}>{k.code}</option>)}</select></Field><Field label="Loại chi phí"><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{["Sửa chữa","Bảo trì","Vệ sinh","Điện nước chung","Khác"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Nội dung"><input required value={f.content} onChange={e=>setF({...f,content:e.target.value})}/></Field><Field label="Số tiền"><input type="number" min="0" value={f.amount} onChange={e=>setF({...f,amount:Number(e.target.value)})}/></Field><Field label="Bên chịu"><select value={f.payer} onChange={e=>setF({...f,payer:e.target.value,addToBill:e.target.value==="Khách hàng"})}><option>Chủ mặt bằng</option><option>Khách hàng</option></select></Field><label className="check"><input type="checkbox" checked={f.addToBill} onChange={e=>setF({...f,addToBill:e.target.checked})}/> Đưa vào bill tháng</label></FormModal>}
function BillDetail({bill,customer,kiosk,onClose,onPay,onPdf}:{bill:Row;customer?:Row;kiosk?:Row;onClose:()=>void;onPay:()=>void;onPdf:()=>void}){const items=[["Tiền thuê",bill.rent],["Tiền điện",bill.electric],["Tiền nước",bill.water],["Phí quản lý",bill.managementFee],["Phí dịch vụ",bill.serviceFee],["Phí khác",bill.otherFee],["Giảm giá",-bill.discount]];return <Modal title={`Bill ${bill.period}`} onClose={onClose}><div className="invoice"><div className="invoice-head"><div><small>KHÁCH HÀNG</small><strong>{customer?.name}</strong><span>{customer?.brand}</span></div><div><small>KIOSK</small><strong>{kiosk?.code}</strong><span>Hạn {dateVi(bill.dueDate)}</span></div></div>{items.map(([label,value])=><div className="invoice-line" key={String(label)}><span>{label}</span><b>{money(Number(value))}</b></div>)}<div className="invoice-total"><span>Tổng thanh toán</span><strong>{money(bill.total)}</strong></div><div className="invoice-paid"><span>Đã thanh toán {money(bill.paidAmount)}</span><Badge>{bill.status}</Badge></div></div><footer className="modal-actions"><button onClick={onPdf}>Xuất PDF</button>{bill.paidAmount<bill.total&&<button className="primary" onClick={onPay}>Đánh dấu thanh toán</button>}</footer></Modal>}
function DetailModal({title,onClose,rows,sections,actions}:{title:string;onClose:()=>void;rows:[string,any][];sections?:{title:string;text:string}[];actions?:ReactNode}){return <Modal title={title} onClose={onClose}><div className="detail-list">{rows.map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}</div>{sections&&<div className="detail-sections">{sections.map(s=><section key={s.title}><h3>{s.title}</h3><p>{s.text}</p></section>)}</div>}<footer className="modal-actions">{actions}</footer></Modal>}
function FormModal({title,onClose,onSubmit,children}:{title:string;onClose:()=>void;onSubmit:()=>void;children:ReactNode}){const submit=(e:FormEvent)=>{e.preventDefault();onSubmit()};return <Modal title={title} onClose={onClose}><form className="modal-form" onSubmit={submit}>{children}<footer className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary" type="submit">Lưu</button></footer></form></Modal>}
function TextFields({form,setForm,fields}:{form:Row;setForm:(x:Row)=>void;fields:[string,string,string?][]}){return <>{fields.map(([key,label,type])=><Field label={label} key={key}><input type={type??"text"} required={!["email"].includes(type??"")} value={form[key]??""} onChange={e=>setForm({...form,[key]:type==="number"?Number(e.target.value):e.target.value})}/></Field>)}</>}
